#!/bin/bash

help() {
  echo "Usage:"
  echo "  zpackage remove web-terminal"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi
  
  if [ "$(os::is_nodejs_installed)" = "false" ]; then
    zpackage install nodejs
  fi

  pm::npm remove -g @cliz/web-terminal
}

run() {
  core $@
}

run $@
